# .github/workflows/trigger-gitlab-ci.yml
name: Trigger GitLab CI

on:
  pull_request:
    branches:
      - main
      - development
      - staging

jobs:
  trigger-gitlab-ci:
    runs-on: ubuntu-latest
    steps:
      - name: trigger Job
        uses: appleboy/gitlab-ci-action@v1.3.0
        with:
          host: "https://gitlab.com"
          token: ${{ secrets.GITLAB_PAT }}
          debug: true
          project_id: ${{ secrets.GITLAB_PROJECT_ID }}
          ref: ${{ github.head_ref }}
